#!/usr/bin/env python3
"""
离线转换脚本：读取含 /lidar_packets 的 MCAP，
解析万集 WLR-722Z 数据包，将每帧 /lidar_points 写入新 MCAP。

生成的新 MCAP 可直接在 Foxglove Desktop 打开，
在 3D panel 订阅 /lidar_points 即可可视化点云。

输出 schema: sensor_msgs/PointCloud2 (ROS2)
  fields: x(f32), y(f32), z(f32), intensity(f32)
  frame_id: lidar
  is_bigendian: false
  is_dense: true

用法:
  python3 mcap_add_lidar_points.py <input.mcap> [output.mcap]

依赖:
  pip install mcap mcap-ros2-support numpy
"""

import sys
import struct
import math
import time
import argparse
from pathlib import Path

import numpy as np

# ── 尝试导入 MCAP 库 ──────────────────────────────────────────────────────────
try:
    from mcap.reader import make_reader
    from mcap.writer import Writer
except ImportError:
    print("错误: 请安装 mcap 库: pip install mcap")
    sys.exit(1)

# ── 配置 ──────────────────────────────────────────────────────────────────────
TOPIC_IN   = "/lidar_packets"
TOPIC_OUT  = "/lidar_points"
FRAME_ID   = "lidar"

# 校准文件路径 (相对本脚本目录)
CALIB_CSV  = Path(__file__).parent.parent / "config" / "calibration" / "Vanjee_722z_VA.csv"

# 距离参数
DISTANCE_RES = 0.002
DISTANCE_MIN = 0.01
DISTANCE_MAX = 100.0

# 光心偏移
OPTCENT_ARG  = 21570   # 毫度
OPTCENT_L    = 0.02067 # 米
OPTCENT_Z    = 0.00795 # 米

# foxglove.PointCloud schema (JSON Schema encoding)
# Foxglove Desktop 原生支持，无需额外依赖类型
FOXGLOVE_PC_SCHEMA = b"""{
  "title": "foxglove.PointCloud",
  "description": "A collection of N-dimensional points",
  "$comment": "Generated by mcap_add_lidar_points.py",
  "type": "object",
  "properties": {
    "timestamp": {
      "type": "object",
      "properties": {
        "sec":  {"type": "integer"},
        "nsec": {"type": "integer"}
      }
    },
    "frame_id": {"type": "string"},
    "pose": {
      "type": "object",
      "properties": {
        "position":    {"type": "object", "properties": {"x":{"type":"number"},"y":{"type":"number"},"z":{"type":"number"}}},
        "orientation": {"type": "object", "properties": {"x":{"type":"number"},"y":{"type":"number"},"z":{"type":"number"},"w":{"type":"number"}}}
      }
    },
    "point_stride": {"type": "integer"},
    "fields": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "name":   {"type": "string"},
          "offset": {"type": "integer"},
          "type":   {"type": "integer"}
        }
      }
    },
    "data": {"type": "string", "contentEncoding": "base64"}
  }
}"""

# ── 三角函数查找表 ────────────────────────────────────────────────────────────
_cos_table = None
_sin_table = None

def init_trig_tables():
    global _cos_table, _sin_table
    if _cos_table is not None:
        return
    angles_rad = np.arange(360000) * math.pi / 180000.0
    _cos_table = np.cos(angles_rad).astype(np.float64)
    _sin_table = np.sin(angles_rad).astype(np.float64)

def COS(angle_millideg):
    return _cos_table[int(angle_millideg) % 360000]

def SIN(angle_millideg):
    return _sin_table[int(angle_millideg) % 360000]

# ── 校准文件加载 ──────────────────────────────────────────────────────────────
def load_calibration(csv_path):
    vert_angles  = []
    horiz_angles = []
    with open(csv_path, 'r') as f:
        for line in f:
            line = line.strip()
            if not line:
                continue
            parts = line.split(',')
            vert_angles.append(int(float(parts[0]) * 1000))   # 毫度
            horiz_angles.append(int(float(parts[1]) * 1000))  # 毫度
    return vert_angles, horiz_angles

# ── CRC32/MPEG-2 ──────────────────────────────────────────────────────────────
def crc32mpeg2(data, length):
    crc = 0xFFFFFFFF
    for i in range(length):
        crc ^= (data[i] << 24)
        for _ in range(8):
            if crc & 0x80000000:
                crc = ((crc << 1) ^ 0x04C11DB7) & 0xFFFFFFFF
            else:
                crc = (crc << 1) & 0xFFFFFFFF
    return crc

# ── CDR 解析 ──────────────────────────────────────────────────────────────────
def parse_cdr(raw_data):
    if len(raw_data) < 20:
        return None
    offset = 4  # skip CDR header
    offset += 8  # stamp.sec + stamp.nanosec
    str_len = struct.unpack_from('<I', raw_data, offset)[0]
    offset += 4 + str_len
    offset = (offset + 3) & ~3
    data_len = struct.unpack_from('<I', raw_data, offset)[0]
    offset += 4
    return raw_data[offset:offset + data_len]

# ── 子包扫描 ──────────────────────────────────────────────────────────────────
def extract_sub_packets(data):
    packets = []
    i = 0
    while i < len(data) - 1:
        if data[i] != 0xEE:
            i += 1
            continue
        if data[i + 1] == 0xFF:
            if i + 6 > len(data):
                break
            dtype = data[i + 5]
            if dtype == 0x00 and i + 80 <= len(data):
                packets.append(data[i:i+80])
                i += 80
            elif dtype == 0x01 and i + 34 <= len(data):
                i += 34
            else:
                i += 1
        elif data[i + 1] == 0xDD:
            i += 41 if i + 41 <= len(data) else 1
        else:
            i += 1
    return packets

# ── 80 字节点云包解析 ─────────────────────────────────────────────────────────
def decode_packet(pkt, vert_angles, horiz_angles):
    if len(pkt) != 80 or pkt[0] != 0xEE or pkt[1] != 0xFF or pkt[5] != 0x00:
        return None
    crc_calc = crc32mpeg2(pkt, 76)
    crc_pkg  = pkt[76] | (pkt[77] << 8) | (pkt[78] << 16) | (pkt[79] << 24)
    if crc_calc != crc_pkg:
        return None

    azimuth = struct.unpack_from('<H', pkt, 16)[0] % 36000
    optcent_hor = (azimuth * 10 + OPTCENT_ARG + 360000) % 360000

    points = []
    for chan in range(16):
        off = 18 + chan * 3
        dist_raw     = struct.unpack_from('<H', pkt, off)[0]
        reflectivity = pkt[off + 2]
        distance = dist_raw * DISTANCE_RES
        if not (DISTANCE_MIN <= distance <= DISTANCE_MAX):
            continue

        horiz_final = (horiz_angles[chan] + azimuth * 10 + 360000) % 360000
        xy = distance * COS(vert_angles[chan])
        x  = xy * SIN(horiz_final)      + OPTCENT_L * SIN(optcent_hor)
        y  = xy * COS(horiz_final)      + OPTCENT_L * COS(optcent_hor)
        z  = distance * SIN(vert_angles[chan]) + OPTCENT_Z
        points.append((float(x), float(y), float(z), float(reflectivity)))

    return azimuth, points

# ── 序列化 sensor_msgs/PointCloud2 (CDR) ─────────────────────────────────────
#
# CDR layout (little-endian):
#   [0:4]   CDR encapsulation  0x00 0x01 0x00 0x00
#   header.stamp.sec     (int32)
#   header.stamp.nanosec (uint32)
#   header.frame_id      (uint32 len + bytes + padding)
#   height    (uint32)  = 1
#   width     (uint32)  = N (点数)
#   fields[]  (sequence): 4 个 PointField
#   is_bigendian (bool, 1 byte, padded to 1)
#   point_step   (uint32) = 16
#   row_step     (uint32) = N * 16
#   data[]       (sequence: uint32 len + raw bytes)
#   is_dense     (bool)
#
def encode_foxglove_pointcloud(timestamp_ns, points):
    """
    序列化为 foxglove.PointCloud JSON 消息。
    data 字段用 base64 编码的二进制点数据 (x f32, y f32, z f32, intensity f32)。
    """
    import base64, json
    POINT_STEP = 16
    sec  = int(timestamp_ns // 1_000_000_000)
    nsec = int(timestamp_ns %  1_000_000_000)
    N    = len(points)

    pt_buf = bytearray(N * POINT_STEP)
    for i, (x, y, z, intensity) in enumerate(points):
        struct.pack_into('<ffff', pt_buf, i * POINT_STEP, x, y, z, intensity)

    msg = {
        "timestamp": {"sec": sec, "nsec": nsec},
        "frame_id":  FRAME_ID,
        "pose": {
            "position":    {"x": 0.0, "y": 0.0, "z": 0.0},
            "orientation": {"x": 0.0, "y": 0.0, "z": 0.0, "w": 1.0},
        },
        "point_stride": POINT_STEP,
        "fields": [
            {"name": "x",         "offset": 0,  "type": 7},
            {"name": "y",         "offset": 4,  "type": 7},
            {"name": "z",         "offset": 8,  "type": 7},
            {"name": "intensity", "offset": 12, "type": 7},
        ],
        "data": base64.b64encode(bytes(pt_buf)).decode('ascii'),
    }
    return json.dumps(msg).encode('utf-8')

# ── 主流程 ────────────────────────────────────────────────────────────────────
def main():
    parser = argparse.ArgumentParser(
        description="将 /lidar_packets MCAP 转换为含 /lidar_points 的新 MCAP"
    )
    parser.add_argument("input",  help="输入 MCAP 文件路径")
    parser.add_argument("output", nargs='?', help="输出 MCAP 文件路径 (默认: <input>_with_points.mcap)")
    parser.add_argument("--calibration", "-c", default=str(CALIB_CSV),
                        help=f"角度校准 CSV 路径 (默认: {CALIB_CSV})")
    parser.add_argument("--max-frames", "-n", type=int, default=None,
                        help="最多处理帧数 (默认: 全部)")
    args = parser.parse_args()

    input_path = Path(args.input)
    if not input_path.exists():
        print(f"错误: 输入文件不存在: {input_path}")
        sys.exit(1)

    output_path = Path(args.output) if args.output else \
        input_path.with_name(input_path.stem + "_with_points.mcap")

    calib_path = Path(args.calibration)
    if not calib_path.exists():
        print(f"错误: 校准文件不存在: {calib_path}")
        sys.exit(1)

    print("=" * 60)
    print("万集 WLR-722Z — MCAP 点云转换工具")
    print("=" * 60)
    print(f"  输入:   {input_path}")
    print(f"  输出:   {output_path}")
    print(f"  校准:   {calib_path}")

    # 初始化
    init_trig_tables()
    vert_angles, horiz_angles = load_calibration(calib_path)
    print(f"  通道数: {len(vert_angles)}")

    t_start = time.time()

    # 帧分割状态
    frame_points      = []
    frame_ts_ns       = None
    frame_count       = 0
    pkt_total         = 0
    pkt_crc_fail      = 0
    prev_azimuth_trans = -1

    with open(input_path, 'rb') as fin, open(output_path, 'wb') as fout:
        writer = Writer(fout)
        writer.start()

        # 注册 schema 和 channel (foxglove.PointCloud, jsonschema encoding)
        schema_id = writer.register_schema(
            name="foxglove.PointCloud",
            encoding="jsonschema",
            data=FOXGLOVE_PC_SCHEMA,
        )
        channel_id = writer.register_channel(
            topic=TOPIC_OUT,
            message_encoding="json",
            schema_id=schema_id,
        )

        reader = make_reader(fin)
        for schema, channel, message in reader.iter_messages(topics=[TOPIC_IN]):
            ts_ns = message.publish_time

            data_bytes = parse_cdr(message.data)
            if not data_bytes:
                continue

            sub_pkts = extract_sub_packets(data_bytes)
            for pkt in sub_pkts:
                pkt_total += 1
                result = decode_packet(pkt, vert_angles, horiz_angles)
                if result is None:
                    pkt_crc_fail += 1
                    continue

                azimuth, points = result

                if frame_ts_ns is None:
                    frame_ts_ns = ts_ns

                # 帧切割（纯回落检测，对齐驱动逻辑）
                azimuth_trans = (azimuth + 60) % 36000
                if prev_azimuth_trans >= 0 and azimuth_trans < prev_azimuth_trans:
                    if frame_points:
                        frame_count += 1
                        json_data = encode_foxglove_pointcloud(frame_ts_ns, frame_points)
                        writer.add_message(
                            channel_id=channel_id,
                            log_time=frame_ts_ns,
                            data=json_data,
                            publish_time=frame_ts_ns,
                        )
                        print(f"  帧 {frame_count:4d}: {len(frame_points):6d} 点  "
                              f"t={frame_ts_ns/1e9:.3f}s")
                        frame_points = []
                        frame_ts_ns  = None

                        if args.max_frames and frame_count >= args.max_frames:
                            print(f"\n已达到最大帧数 ({args.max_frames})，停止")
                            break

                prev_azimuth_trans = azimuth_trans
                frame_points.extend(points)

            else:
                # 内层循环正常结束（未 break），继续外层
                continue
            break  # 内层触发 break，传播到外层

        # 保存最后一帧
        if frame_points:
            frame_count += 1
            json_data = encode_foxglove_pointcloud(
                frame_ts_ns if frame_ts_ns else 0, frame_points
            )
            writer.add_message(
                channel_id=channel_id,
                log_time=frame_ts_ns or 0,
                data=json_data,
                publish_time=frame_ts_ns or 0,
            )
            print(f"  帧 {frame_count:4d}: {len(frame_points):6d} 点  (最后一帧)")

        writer.finish()

    elapsed = time.time() - t_start
    print(f"\n{'=' * 60}")
    print(f"完成!")
    print(f"  总子包数:     {pkt_total}")
    print(f"  CRC 失败:     {pkt_crc_fail}")
    print(f"  写入帧数:     {frame_count}")
    print(f"  输出文件:     {output_path}")
    print(f"  耗时:         {elapsed:.1f} 秒")
    print(f"\n在 Foxglove Desktop 中:")
    print(f"  1. 打开 {output_path.name}")
    print(f"  2. 添加 3D panel，订阅 {TOPIC_OUT}")
    print(f"  3. 点云即可显示")
    print("=" * 60)


if __name__ == "__main__":
    main()
